name: Update Contribs & reviewers

on:
  workflow_dispatch:
  schedule:
    # Runs on the 1 and 15 of each month at 00:00 UTC (see https://crontab.guru)
    - cron: "0 0 1,15 * *"

permissions: {}

jobs:
  run-meta:
    if: github.repository_owner == 'pyopensci'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        with:
          persist-credentials: false
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v5
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python -m pip install --upgrade pip wheel
      - name: Install pyosmeta and run update contribs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install dev version
          python -m pip install .
          update-contributors
          update-reviews
          update-review-teams

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725  # v8.0.0
        with:
          # Custom token needed to trigger PR checks, as GITHUB_TOKEN won't
          # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ secrets.PYOS_PR_TOKEN }}
          add-paths: |
            _data/contributors.yml
            _data/packages.yml
          author: Leah <leah@pyopensci.org>
          base: main
          branch: contribs
          commit-message: "Update: Contributor & review file update"
          delete-branch: true
          title: Update contributor and review data
          labels: |
            pre-commit.ci autofix
